-- =============================================================================
-- Beale's CRM — initial schema
-- =============================================================================
-- Everything the app will ever need is created here, so later phases add
-- screens rather than restructuring tables.
--
-- Conventions used throughout:
--   * uuid primary keys, generated by the database
--   * timestamptz for every point in time (never bare timestamp)
--   * numeric(12,2) for money (never float — floats lose cents)
--   * deleted_at for soft delete on records people can remove by mistake
--   * every table has RLS enabled and an explicit policy, no exceptions
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Enumerated types
-- -----------------------------------------------------------------------------
-- Enums are used only for values the application code branches on. Anything an
-- admin should be able to rename later (property types, deal stages, loss
-- reasons) is a lookup table instead — renaming an enum value needs a migration.

create type user_role              as enum ('admin', 'leadership', 'field');
create type account_status         as enum ('prospect', 'active', 'former');
create type building_status        as enum ('pending', 'active', 'lost');
create type operating_entity       as enum ('beales', 'afs');
create type employee_status        as enum ('active', 'terminated', 'leave');
create type contract_change_reason as enum ('initial', 'increase', 'decrease',
                                            'scope_add', 'scope_reduction', 'lost');
create type activity_source        as enum ('manual', 'granola', 'gmail', 'outlook');
create type project_status         as enum ('quoted', 'scheduled', 'in_progress',
                                            'completed', 'cancelled', 'invoiced');
create type parse_status           as enum ('pending', 'parsed', 'needs_review', 'approved');
create type staffing_line_status   as enum ('unmatched', 'matched', 'ignored');
create type attachment_kind        as enum ('before', 'after', 'document', 'photo');
create type audit_action           as enum ('insert', 'update', 'delete');
create type loss_reason_scope      as enum ('building', 'opportunity', 'both');
create type import_status          as enum ('draft', 'previewed', 'committed', 'rolled_back');


-- -----------------------------------------------------------------------------
-- 2. People who can sign in
-- -----------------------------------------------------------------------------
-- Supabase owns auth.users. This mirrors it so the rest of the schema has
-- something to point foreign keys at, and so we can store role and rate access.

create table profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text        not null default '',
  email       text        not null,
  role        user_role   not null default 'leadership',
  -- Pay rates, bill rates, and labour margin are visible only where this is true.
  sees_rates  boolean     not null default false,
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on column profiles.sees_rates is
  'Controls access to employee pay rates, bill rates and labour margin.';

-- A profile row is created automatically whenever an admin invites a user.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- -----------------------------------------------------------------------------
-- 3. Permission helpers
-- -----------------------------------------------------------------------------
-- security definer so they can read profiles without tripping over the very
-- RLS policies that call them.

create function public.is_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_active
  );
$$;

create function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_active and p.role = 'admin'
  );
$$;

create function public.can_see_rates()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_active and p.sees_rates
  );
$$;


-- -----------------------------------------------------------------------------
-- 4. Shared triggers
-- -----------------------------------------------------------------------------

create function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;


-- -----------------------------------------------------------------------------
-- 5. Reference data (admin-editable lookups)
-- -----------------------------------------------------------------------------

create table property_types (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

create table project_types (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

create table service_types (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

create table activity_types (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  icon       text,
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

create table lead_sources (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

create table loss_reasons (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  applies_to loss_reason_scope not null default 'both',
  sort_order integer not null default 0,
  is_active  boolean not null default true
);

create table competitors (
  id         uuid primary key default gen_random_uuid(),
  name       text not null unique,
  notes      text,
  is_active  boolean not null default true
);

-- Deal stages live in a table, not an enum, because the names are not settled
-- and the weighted pipeline needs a probability per stage.
create table pipeline_stages (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique,
  sort_order  integer not null default 0,
  probability integer not null default 0 check (probability between 0 and 100),
  is_won      boolean not null default false,
  is_lost     boolean not null default false,
  is_active   boolean not null default true,
  check (not (is_won and is_lost))
);


-- -----------------------------------------------------------------------------
-- 6. Imports
-- -----------------------------------------------------------------------------
-- Every row the importer creates carries its batch id, so a bad import is undone
-- with one delete instead of hand-cleaning the portfolio.

create table import_batches (
  id          uuid primary key default gen_random_uuid(),
  source_tab  text not null,
  file_name   text,
  mapping     jsonb not null default '{}'::jsonb,
  row_count   integer not null default 0,
  status      import_status not null default 'draft',
  imported_by uuid references profiles (id),
  created_at  timestamptz not null default now(),
  committed_at timestamptz
);

create table import_row_errors (
  id           uuid primary key default gen_random_uuid(),
  batch_id     uuid not null references import_batches (id) on delete cascade,
  row_number   integer not null,
  raw_row      jsonb,
  error        text not null,
  created_at   timestamptz not null default now()
);


-- -----------------------------------------------------------------------------
-- 7. Accounts, buildings, contacts
-- -----------------------------------------------------------------------------

create table accounts (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  account_type       text,
  status             account_status not null default 'prospect',
  owner_id           uuid references profiles (id),
  hq_address_line1   text,
  hq_address_line2   text,
  hq_city            text,
  hq_state           text,
  hq_postal_code     text,
  primary_contact_id uuid,   -- FK added after contacts exists
  notes              text,
  import_batch_id    uuid references import_batches (id) on delete set null,
  deleted_at         timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table buildings (
  id                   uuid primary key default gen_random_uuid(),
  account_id           uuid not null references accounts (id) on delete restrict,
  name                 text not null,
  address_line1        text,
  address_line2        text,
  city                 text,
  state                text,
  postal_code          text,
  property_type_id     uuid references property_types (id),
  square_footage       integer,
  floors               integer,
  entity               operating_entity not null default 'beales',
  contract_start_date  date,
  contract_end_date    date,
  service_days         boolean not null default false,
  service_nights       boolean not null default false,
  scope_notes          text,
  status               building_status not null default 'pending',
  lost_date            date,
  loss_reason_id       uuid references loss_reasons (id),
  lost_to_competitor_id uuid references competitors (id),
  -- Filled in at Phase 7 when InspectQA is linked. Never fuzzy-matched.
  inspectqa_site_id    text,
  import_batch_id      uuid references import_batches (id) on delete set null,
  deleted_at           timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- The revenue table. A building's monthly value is never a single column,
-- because "what was MRR in March" has to stay answerable after a price change.
create table building_contract_periods (
  id             uuid primary key default gen_random_uuid(),
  building_id    uuid not null references buildings (id) on delete cascade,
  effective_date date not null,
  end_date       date,
  monthly_value  numeric(12,2) not null check (monthly_value >= 0),
  annual_value   numeric(12,2) generated always as (monthly_value * 12) stored,
  change_reason  contract_change_reason not null default 'initial',
  notes          text,
  created_by     uuid references profiles (id),
  import_batch_id uuid references import_batches (id) on delete set null,
  created_at     timestamptz not null default now(),
  check (end_date is null or end_date >= effective_date)
);

-- At most one open-ended period per building.
create unique index building_contract_periods_one_open
  on building_contract_periods (building_id)
  where end_date is null;

create table building_services (
  id              uuid primary key default gen_random_uuid(),
  building_id     uuid not null references buildings (id) on delete cascade,
  service_type_id uuid not null references service_types (id),
  frequency       text,
  notes           text,
  unique (building_id, service_type_id)
);

create table contacts (
  id            uuid primary key default gen_random_uuid(),
  first_name    text not null default '',
  last_name     text not null default '',
  title         text,
  account_id    uuid references accounts (id) on delete set null,
  phone         text,
  mobile        text,
  email         text,
  address_line1 text,
  address_line2 text,
  city          text,
  state         text,
  postal_code   text,
  contact_role  text,
  notes         text,
  import_batch_id uuid references import_batches (id) on delete set null,
  deleted_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  check (first_name <> '' or last_name <> '')
);

alter table accounts
  add constraint accounts_primary_contact_fk
  foreign key (primary_contact_id) references contacts (id) on delete set null;

-- One portfolio manager covers many sites.
create table contact_buildings (
  contact_id       uuid not null references contacts (id) on delete cascade,
  building_id      uuid not null references buildings (id) on delete cascade,
  role_at_building text,
  is_primary       boolean not null default false,
  primary key (contact_id, building_id)
);


-- -----------------------------------------------------------------------------
-- 8. Employees and assignments
-- -----------------------------------------------------------------------------
-- Pay and bill rates are deliberately NOT on these tables. They live in
-- companion tables that only rate-seers can read, because Postgres row-level
-- security cannot hide a single column.

create table employees (
  id                  uuid primary key default gen_random_uuid(),
  first_name          text not null default '',
  last_name           text not null default '',
  phone               text,
  email               text,
  title               text,
  employment_type     text,
  start_date          date,
  end_date            date,
  termination_reason  text,
  status              employee_status not null default 'active',
  supervisor_id       uuid references employees (id) on delete set null,
  paychex_employee_id text,
  import_batch_id     uuid references import_batches (id) on delete set null,
  deleted_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (first_name <> '' or last_name <> '')
);

create table employee_compensation (
  employee_id   uuid primary key references employees (id) on delete cascade,
  base_pay_rate numeric(12,2) check (base_pay_rate >= 0),
  updated_by    uuid references profiles (id),
  updated_at    timestamptz not null default now()
);

-- The employee-to-building join. Source of truth for staff movement: an
-- assignment ending and another starting IS a move, so there is no separate
-- "moves" table that could drift out of sync.
create table employee_assignments (
  id                       uuid primary key default gen_random_uuid(),
  employee_id              uuid not null references employees (id) on delete cascade,
  building_id              uuid not null references buildings (id) on delete cascade,
  scheduled_hours_per_week numeric(6,2) check (scheduled_hours_per_week >= 0),
  shift                    text,
  start_date               date not null,
  end_date                 date,
  end_reason               text,
  import_batch_id          uuid references import_batches (id) on delete set null,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  check (end_date is null or end_date >= start_date)
);

create table employee_assignment_rates (
  assignment_id uuid primary key references employee_assignments (id) on delete cascade,
  pay_rate      numeric(12,2) check (pay_rate >= 0),
  bill_rate     numeric(12,2) check (bill_rate >= 0),
  updated_by    uuid references profiles (id),
  updated_at    timestamptz not null default now()
);


-- -----------------------------------------------------------------------------
-- 9. Opportunities
-- -----------------------------------------------------------------------------

create table opportunities (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  -- Null for new-logo deals: there is no account until it is won.
  account_id          uuid references accounts (id) on delete set null,
  -- Set when a won deal is converted into a building.
  building_id         uuid references buildings (id) on delete set null,
  address_line1       text,
  address_line2       text,
  city                text,
  state               text,
  postal_code         text,
  property_type_id    uuid references property_types (id),
  square_footage      integer,
  incumbent_provider  text,
  current_staff_count integer,
  scope_notes         text,
  stage_id            uuid not null references pipeline_stages (id),
  entity              operating_entity not null default 'beales',
  monthly_value       numeric(12,2) check (monthly_value >= 0),
  annual_value        numeric(12,2) generated always as (monthly_value * 12) stored,
  expected_close_date date,
  actual_close_date   date,
  loss_reason_id      uuid references loss_reasons (id),
  competitor_id       uuid references competitors (id),
  owner_id            uuid references profiles (id),
  lead_source_id      uuid references lead_sources (id),
  import_batch_id     uuid references import_batches (id) on delete set null,
  deleted_at          timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Written by trigger only, so a code path can never forget to record a move.
create table opportunity_stage_events (
  id             uuid primary key default gen_random_uuid(),
  opportunity_id uuid not null references opportunities (id) on delete cascade,
  from_stage_id  uuid references pipeline_stages (id),
  to_stage_id    uuid not null references pipeline_stages (id),
  changed_by     uuid references profiles (id),
  changed_at     timestamptz not null default now()
);

create function public.record_opportunity_stage_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into opportunity_stage_events (opportunity_id, from_stage_id, to_stage_id, changed_by)
    values (new.id, null, new.stage_id, auth.uid());
  elsif new.stage_id is distinct from old.stage_id then
    insert into opportunity_stage_events (opportunity_id, from_stage_id, to_stage_id, changed_by)
    values (new.id, old.stage_id, new.stage_id, auth.uid());
  end if;
  return new;
end;
$$;

create trigger opportunities_stage_events
  after insert or update of stage_id on opportunities
  for each row execute function public.record_opportunity_stage_change();


-- -----------------------------------------------------------------------------
-- 10. Activities
-- -----------------------------------------------------------------------------
-- Only type and subject are required. Everything else is optional, because
-- required fields are what stop people logging anything at all.

create table activities (
  id               uuid primary key default gen_random_uuid(),
  activity_type_id uuid not null references activity_types (id),
  subject          text not null check (subject <> ''),
  body             text,
  occurred_at      timestamptz not null default now(),
  logged_by        uuid references profiles (id),

  -- Optional links. An activity may point at any combination of these.
  account_id       uuid references accounts (id) on delete cascade,
  building_id      uuid references buildings (id) on delete cascade,
  contact_id       uuid references contacts (id) on delete set null,
  opportunity_id   uuid references opportunities (id) on delete cascade,
  employee_id      uuid references employees (id) on delete set null,

  source           activity_source not null default 'manual',
  external_id      text,
  import_batch_id  uuid references import_batches (id) on delete set null,
  created_at       timestamptz not null default now(),

  -- Stops an integration importing the same email twice.
  unique (source, external_id)
);

-- Roll an activity up to its account automatically. Logging a complaint against
-- a building must show on the account timeline, without a join at read time.
create function public.set_activity_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.account_id is null and new.building_id is not null then
    select b.account_id into new.account_id from buildings b where b.id = new.building_id;
  end if;

  if new.account_id is null and new.opportunity_id is not null then
    select o.account_id into new.account_id from opportunities o where o.id = new.opportunity_id;
  end if;

  if new.account_id is null and new.contact_id is not null then
    select c.account_id into new.account_id from contacts c where c.id = new.contact_id;
  end if;

  return new;
end;
$$;

create trigger activities_set_account
  before insert or update of building_id, opportunity_id, contact_id, account_id
  on activities
  for each row execute function public.set_activity_account();


-- -----------------------------------------------------------------------------
-- 11. Projects — periodic and extra work billed on top of the contract
-- -----------------------------------------------------------------------------

create table projects (
  id              uuid primary key default gen_random_uuid(),
  building_id     uuid not null references buildings (id) on delete cascade,
  project_type_id uuid references project_types (id),
  name            text,
  scheduled_date  date,
  completed_date  date,
  quoted_amount   numeric(12,2) check (quoted_amount >= 0),
  invoiced_amount numeric(12,2) check (invoiced_amount >= 0),
  status          project_status not null default 'quoted',
  notes           text,
  import_batch_id uuid references import_batches (id) on delete set null,
  deleted_at      timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table project_employees (
  project_id  uuid not null references projects (id) on delete cascade,
  employee_id uuid not null references employees (id) on delete cascade,
  hours       numeric(6,2) check (hours >= 0),
  primary key (project_id, employee_id)
);


-- -----------------------------------------------------------------------------
-- 12. Attachments — before/after photos, signed contracts, documents
-- -----------------------------------------------------------------------------

create table attachments (
  id           uuid primary key default gen_random_uuid(),
  storage_path text not null,
  file_name    text not null,
  mime_type    text,
  size_bytes   bigint,
  caption      text,
  kind         attachment_kind not null default 'document',
  uploaded_by  uuid references profiles (id),
  created_at   timestamptz not null default now(),

  project_id   uuid references projects (id) on delete cascade,
  building_id  uuid references buildings (id) on delete cascade,
  account_id   uuid references accounts (id) on delete cascade,
  activity_id  uuid references activities (id) on delete cascade
);


-- -----------------------------------------------------------------------------
-- 13. Staffing reports — the weekly payroll emails
-- -----------------------------------------------------------------------------
-- One submission, many employee-hour lines. Parsed rows are reviewable and
-- editable before anyone trusts them.

create table staffing_reports (
  id           uuid primary key default gen_random_uuid(),
  week_ending  date not null,
  submitted_by uuid references profiles (id),
  source       text not null default 'paste',
  raw_text     text,
  parse_status parse_status not null default 'pending',
  reviewed_by  uuid references profiles (id),
  reviewed_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table staffing_report_lines (
  id                 uuid primary key default gen_random_uuid(),
  staffing_report_id uuid not null references staffing_reports (id) on delete cascade,
  building_id        uuid references buildings (id) on delete set null,
  employee_id        uuid references employees (id) on delete set null,
  building_name_raw  text,
  employee_name_raw  text,
  hours              numeric(6,2) check (hours >= 0),
  notes              text,
  line_status        staffing_line_status not null default 'unmatched',
  created_at         timestamptz not null default now()
);


-- -----------------------------------------------------------------------------
-- 14. InspectQA mirrors — read-only copies, never authoritative
-- -----------------------------------------------------------------------------
-- Populated on a schedule from the InspectQA project at Phase 7. The CRM always
-- reads these, so InspectQA being down never breaks the CRM. Nothing here is
-- ever written back.

create table inspectqa_site_map (
  inspectqa_site_id text primary key,
  building_id       uuid not null references buildings (id) on delete cascade,
  site_name_raw     text,
  confirmed_by      uuid references profiles (id),
  confirmed_at      timestamptz,
  created_at        timestamptz not null default now()
);

create table inspections (
  id                uuid primary key default gen_random_uuid(),
  inspectqa_id      text not null unique,
  inspectqa_site_id text,
  building_id       uuid references buildings (id) on delete set null,
  inspected_at      timestamptz,
  inspector_name    text,
  score             numeric(5,2),
  grade             text,
  area_breakdown    jsonb,
  report_url        text,
  synced_at         timestamptz not null default now()
);

create table work_orders (
  id                uuid primary key default gen_random_uuid(),
  inspectqa_id      text not null unique,
  inspectqa_site_id text,
  building_id       uuid references buildings (id) on delete set null,
  description       text,
  priority          text,
  status            text,
  created_at_source timestamptz,
  completed_at      timestamptz,
  synced_at         timestamptz not null default now()
);


-- -----------------------------------------------------------------------------
-- 15. Audit log
-- -----------------------------------------------------------------------------
-- Five people editing shared records. Written by trigger from day one, because
-- history cannot be backfilled later.

create table audit_log (
  id          bigint generated always as identity primary key,
  table_name  text not null,
  record_id   uuid,
  action      audit_action not null,
  changed_by  uuid references profiles (id),
  changed_at  timestamptz not null default now(),
  old_values  jsonb,
  new_values  jsonb
);

create function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_json jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  new_json jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  rec_id   uuid;
begin
  -- Most tables key on "id", but the two rate tables key on the record they
  -- extend, so find the primary key by name rather than assuming new.id exists.
  rec_id := coalesce(
    coalesce(new_json, old_json) ->> 'id',
    coalesce(new_json, old_json) ->> 'assignment_id',
    coalesce(new_json, old_json) ->> 'employee_id'
  )::uuid;

  if tg_op = 'INSERT' then
    insert into audit_log (table_name, record_id, action, changed_by, new_values)
    values (tg_table_name, rec_id, 'insert', auth.uid(), new_json);
    return new;

  elsif tg_op = 'UPDATE' then
    -- Skip no-op updates so the log stays readable. updated_at is ignored
    -- because its own trigger always bumps it, which would make every save look
    -- like a change.
    if (old_json - 'updated_at') is distinct from (new_json - 'updated_at') then
      insert into audit_log (table_name, record_id, action, changed_by, old_values, new_values)
      values (tg_table_name, rec_id, 'update', auth.uid(), old_json, new_json);
    end if;
    return new;

  else
    insert into audit_log (table_name, record_id, action, changed_by, old_values)
    values (tg_table_name, rec_id, 'delete', auth.uid(), old_json);
    return old;
  end if;
end;
$$;


-- -----------------------------------------------------------------------------
-- 16. Attach the shared triggers
-- -----------------------------------------------------------------------------

do $$
declare
  t text;
  -- Tables carrying updated_at.
  touched text[] := array[
    'profiles', 'accounts', 'buildings', 'contacts', 'employees',
    'employee_assignments', 'opportunities', 'projects', 'staffing_reports'
  ];
  -- Tables worth keeping an edit history for.
  audited text[] := array[
    'accounts', 'buildings', 'building_contract_periods', 'contacts',
    'employees', 'employee_assignments', 'employee_compensation',
    'employee_assignment_rates', 'opportunities', 'activities', 'projects'
  ];
begin
  foreach t in array touched loop
    execute format(
      'create trigger %I_touch_updated_at before update on %I
         for each row execute function public.touch_updated_at()', t, t);
  end loop;

  foreach t in array audited loop
    execute format(
      'create trigger %I_audit after insert or update or delete on %I
         for each row execute function public.write_audit_log()', t, t);
  end loop;
end;
$$;


-- -----------------------------------------------------------------------------
-- 17. Indexes
-- -----------------------------------------------------------------------------
-- Foreign keys used for filtering, plus the sort orders the timelines rely on.

create index buildings_account_idx            on buildings (account_id) where deleted_at is null;
create index buildings_status_idx             on buildings (status);
create index buildings_entity_idx             on buildings (entity);
create index contract_periods_building_idx    on building_contract_periods (building_id, effective_date desc);
create index building_services_building_idx   on building_services (building_id);
create index contacts_account_idx             on contacts (account_id) where deleted_at is null;
create index contacts_email_idx               on contacts (lower(email));
create index contact_buildings_building_idx   on contact_buildings (building_id);
create index employees_supervisor_idx         on employees (supervisor_id);
create index assignments_building_idx         on employee_assignments (building_id, start_date desc);
create index assignments_employee_idx         on employee_assignments (employee_id, start_date desc);
create index assignments_open_idx             on employee_assignments (building_id) where end_date is null;
create index opportunities_stage_idx          on opportunities (stage_id) where deleted_at is null;
create index opportunities_account_idx        on opportunities (account_id) where deleted_at is null;
create index opportunities_owner_idx          on opportunities (owner_id) where deleted_at is null;
create index stage_events_opportunity_idx     on opportunity_stage_events (opportunity_id, changed_at);
create index activities_account_time_idx      on activities (account_id, occurred_at desc);
create index activities_building_time_idx     on activities (building_id, occurred_at desc);
create index activities_contact_time_idx      on activities (contact_id, occurred_at desc);
create index activities_opportunity_time_idx  on activities (opportunity_id, occurred_at desc);
create index activities_logged_by_time_idx    on activities (logged_by, occurred_at desc);
create index activities_time_idx              on activities (occurred_at desc);
create index projects_building_idx            on projects (building_id) where deleted_at is null;
create index attachments_project_idx          on attachments (project_id);
create index attachments_building_idx         on attachments (building_id);
create index staffing_lines_report_idx        on staffing_report_lines (staffing_report_id);
create index inspections_building_idx         on inspections (building_id, inspected_at desc);
create index work_orders_building_idx         on work_orders (building_id);
create index audit_log_record_idx             on audit_log (table_name, record_id, changed_at desc);


-- -----------------------------------------------------------------------------
-- 18. Contract value helper
-- -----------------------------------------------------------------------------
-- The building form shows one "monthly value" field. This is what it calls:
-- close the current period, open a new one. History accrues by itself.

create function public.set_building_monthly_value(
  p_building_id    uuid,
  p_monthly_value  numeric,
  p_effective_date date default current_date,
  p_reason         contract_change_reason default null,
  p_notes          text default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_current  building_contract_periods;
  v_reason   contract_change_reason;
  v_new_id   uuid;
begin
  select * into v_current
  from building_contract_periods
  where building_id = p_building_id and end_date is null
  order by effective_date desc
  limit 1;

  -- Nothing changed — leave history alone.
  if found and v_current.monthly_value = p_monthly_value then
    return v_current.id;
  end if;

  v_reason := coalesce(
    p_reason,
    case
      when not found then 'initial'::contract_change_reason
      when p_monthly_value > v_current.monthly_value then 'increase'::contract_change_reason
      else 'decrease'::contract_change_reason
    end
  );

  if found then
    update building_contract_periods
    set end_date = greatest(p_effective_date - 1, effective_date)
    where id = v_current.id;
  end if;

  insert into building_contract_periods
    (building_id, effective_date, monthly_value, change_reason, notes, created_by)
  values
    (p_building_id, p_effective_date, p_monthly_value, v_reason, p_notes, auth.uid())
  returning id into v_new_id;

  return v_new_id;
end;
$$;

-- Marking a building lost also stops its revenue. Churn in the waterfall comes
-- from a period ending, never from the status column alone.
create function public.close_building_contract(
  p_building_id uuid,
  p_lost_date   date default current_date
)
returns void
language sql
security invoker
set search_path = public
as $$
  update building_contract_periods
  set end_date = greatest(p_lost_date, effective_date),
      change_reason = 'lost'
  where building_id = p_building_id and end_date is null;
$$;


-- -----------------------------------------------------------------------------
-- 19. Revenue and reporting views
-- -----------------------------------------------------------------------------
-- All revenue maths lives here. React never computes MRR.
-- security_invoker = on so these obey the caller's RLS rather than the owner's.

create view v_building_current_value
with (security_invoker = on) as
select
  b.id            as building_id,
  b.account_id,
  b.entity,
  b.status,
  p.monthly_value,
  p.annual_value,
  p.effective_date
from buildings b
left join building_contract_periods p
  on p.building_id = b.id and p.end_date is null
where b.deleted_at is null;

create view v_building_mrr_by_month
with (security_invoker = on) as
select
  b.id          as building_id,
  b.account_id,
  b.entity,
  b.property_type_id,
  m.month::date as month,
  p.monthly_value
from buildings b
join lateral generate_series(
       (select date_trunc('month', min(bcp.effective_date))
          from building_contract_periods bcp
         where bcp.building_id = b.id),
       date_trunc('month', now()),
       interval '1 month'
     ) as m(month) on true
join lateral (
  select bcp.monthly_value
  from building_contract_periods bcp
  where bcp.building_id = b.id
    and bcp.effective_date < (m.month + interval '1 month')
    and (bcp.end_date is null or bcp.end_date >= m.month::date)
  order by bcp.effective_date desc
  limit 1
) p on true
where b.deleted_at is null;

create view v_account_mrr_by_month
with (security_invoker = on) as
select
  a.id   as account_id,
  a.name as account_name,
  v.month,
  sum(v.monthly_value) as mrr
from accounts a
join v_building_mrr_by_month v on v.account_id = a.id
where a.deleted_at is null
group by a.id, a.name, v.month;

-- New business / expansion / contraction / churn, month by month.
create view v_mrr_waterfall
with (security_invoker = on) as
with monthly as (
  select building_id, entity, month, monthly_value from v_building_mrr_by_month
),
compared as (
  select
    coalesce(cur.month, (prev.month + interval '1 month')::date) as month,
    coalesce(cur.entity, prev.entity)                            as entity,
    coalesce(cur.monthly_value, 0)                               as current_value,
    coalesce(prev.monthly_value, 0)                              as prev_value,
    cur.building_id  is null                                     as churned,
    prev.building_id is null                                     as is_new
  from monthly cur
  full outer join monthly prev
    on prev.building_id = cur.building_id
   and prev.month = (cur.month - interval '1 month')::date
)
select
  month,
  entity,
  sum(case when is_new then current_value else 0 end)                                        as new_business,
  sum(case when not is_new and not churned and current_value > prev_value
           then current_value - prev_value else 0 end)                                       as expansion,
  sum(case when not is_new and not churned and current_value < prev_value
           then prev_value - current_value else 0 end)                                       as contraction,
  sum(case when churned then prev_value else 0 end)                                          as churn,
  sum(current_value)                                                                         as ending_mrr
from compared
-- The full outer join reaches one month past the last billed month, which would
-- otherwise show every live building churning next month.
where month <= date_trunc('month', now())::date
group by month, entity;

create view v_weighted_pipeline
with (security_invoker = on) as
select
  o.id as opportunity_id,
  o.name,
  o.account_id,
  o.owner_id,
  o.entity,
  s.name as stage_name,
  s.sort_order as stage_sort_order,
  o.monthly_value,
  o.annual_value,
  s.probability,
  round(coalesce(o.annual_value, 0) * s.probability / 100.0, 2) as weighted_annual_value,
  o.expected_close_date
from opportunities o
join pipeline_stages s on s.id = o.stage_id
where o.deleted_at is null
  and not s.is_won
  and not s.is_lost;

-- An assignment ending and another beginning is a move.
create view v_staff_movement
with (security_invoker = on) as
select
  e.id                as employee_id,
  e.first_name,
  e.last_name,
  prev.building_id    as from_building_id,
  next_a.building_id  as to_building_id,
  prev.end_date       as moved_on,
  next_a.start_date   as started_on,
  prev.end_reason
from employees e
join employee_assignments prev on prev.employee_id = e.id and prev.end_date is not null
left join lateral (
  select a.building_id, a.start_date
  from employee_assignments a
  where a.employee_id = e.id
    and a.start_date >= prev.end_date
    and a.id <> prev.id
  order by a.start_date
  limit 1
) next_a on true
where e.deleted_at is null;

-- Labour margin. Restricted by RLS on employee_assignment_rates: this returns
-- no rows at all for anyone without rate access.
create view v_building_labor_margin
with (security_invoker = on) as
select
  a.building_id,
  b.account_id,
  sum(a.scheduled_hours_per_week)                                    as scheduled_hours_per_week,
  sum(a.scheduled_hours_per_week * r.bill_rate)                      as weekly_billed,
  sum(a.scheduled_hours_per_week * r.pay_rate)                       as weekly_cost,
  sum(a.scheduled_hours_per_week * (r.bill_rate - r.pay_rate))       as weekly_margin
from employee_assignments a
join employee_assignment_rates r on r.assignment_id = a.id
join buildings b on b.id = a.building_id
where a.end_date is null and b.deleted_at is null
group by a.building_id, b.account_id;


-- -----------------------------------------------------------------------------
-- 20. Row Level Security
-- -----------------------------------------------------------------------------
-- All five people share all data, so the base rule is "you are an active
-- profile". With five trusted users this is a blast door against a leaked anon
-- key, not an internal permission system — the two real exceptions are pay
-- rates and admin-only reference data.

do $$
declare
  t text;
  -- Everyday records: any signed-in member reads and writes.
  member_rw text[] := array[
    'accounts', 'buildings', 'building_contract_periods', 'building_services',
    'contacts', 'contact_buildings', 'employees', 'employee_assignments',
    'opportunities', 'activities', 'projects', 'project_employees',
    'attachments', 'staffing_reports', 'staffing_report_lines', 'competitors'
  ];
  -- Reference data: everyone reads, admins change.
  admin_managed text[] := array[
    'property_types', 'project_types', 'service_types', 'activity_types',
    'lead_sources', 'loss_reasons', 'pipeline_stages',
    'import_batches', 'import_row_errors', 'inspectqa_site_map'
  ];
  -- Pay and margin: only profiles with sees_rates.
  rate_tables text[] := array['employee_compensation', 'employee_assignment_rates'];
  -- Written by the sync job (service role) only; everyone reads.
  read_only text[] := array['inspections', 'work_orders'];
begin
  foreach t in array member_rw loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy members_select on %I for select to authenticated using (public.is_member())', t);
    execute format('create policy members_insert on %I for insert to authenticated with check (public.is_member())', t);
    execute format('create policy members_update on %I for update to authenticated using (public.is_member()) with check (public.is_member())', t);
    execute format('create policy members_delete on %I for delete to authenticated using (public.is_member())', t);
  end loop;

  foreach t in array admin_managed loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy members_select on %I for select to authenticated using (public.is_member())', t);
    execute format('create policy admins_write on %I for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;

  foreach t in array rate_tables loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy rate_viewers_all on %I for all to authenticated using (public.can_see_rates()) with check (public.can_see_rates())', t);
  end loop;

  foreach t in array read_only loop
    execute format('alter table %I enable row level security', t);
    execute format('create policy members_select on %I for select to authenticated using (public.is_member())', t);
    -- No insert/update/delete policy: only the service role can write these.
  end loop;
end;
$$;

-- profiles: everyone sees the team; you edit yourself; admins edit anyone.
alter table profiles enable row level security;

create policy profiles_select on profiles
  for select to authenticated using (public.is_member());

create policy profiles_update_self on profiles
  for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

create policy profiles_admin_all on profiles
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- opportunity_stage_events: readable by all, written only by the trigger.
alter table opportunity_stage_events enable row level security;

create policy stage_events_select on opportunity_stage_events
  for select to authenticated using (public.is_member());

-- audit_log: readable by all, written only by the trigger.
alter table audit_log enable row level security;

create policy audit_log_select on audit_log
  for select to authenticated using (public.is_member());


-- -----------------------------------------------------------------------------
-- 21. Grants
-- -----------------------------------------------------------------------------
-- RLS decides which rows. These decide which tables are visible at all.

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
